# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8xjIYZVo3iJOS-3CBBI_f8HQT1N37Be
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    'Song': ['Blinding Lights', 'Shape of You', 'Levitating', "God's Plan", 'SICKO MODE', 'HUMBLE.', 'Believer', 'Bohemian Rhapsody', 'Closer', 'Animals', 'Titanium', 'Tum Hi Ho', 'Kesariya', 'Channa Mereya', 'Perfect', 'All of Me', 'Let Her Go'],
    'Genre': ['Pop', 'Pop', 'Pop', 'Hip-Hop', 'Hip-Hop', 'Hip-Hop', 'Rock', 'Rock', 'EDM', 'EDM', 'EDM', 'Bollywood', 'Bollywood', 'Bollywood', 'Romance', 'Romance', 'Romance'],
    'PlayCount': [1500, 1800, 1400, 1700, 1600, 1550, 1450, 1750, 1650, 1500, 1550, 1800, 1700, 1750, 1600, 1500, 1450]
}

df = pd.DataFrame(data)
df.to_csv('songs.csv', index=False)
df = pd.read_csv('songs.csv')

print("Dataset Loaded\n")
print(df.head())

df.dropna(inplace=True)
df['Genre'] = df['Genre'].str.lower()

print("\nCleaned Data\n", df.head())

genre_map = {g: i for i, g in enumerate(df['Genre'].unique())}
df['GenreEncoded'] = df['Genre'].map(genre_map)

X = df[['GenreEncoded']].values
y = df['PlayCount'].values

w = np.random.randn(1)
b = 0.0

lr = 0.01
epochs = 40

losses = []

print("\nTraining Started\n")

for epoch in range(epochs):
    y_pred = X.flatten() * w + b
    loss = np.mean((y - y_pred) ** 2)
    losses.append(loss)

    dw = -2 * np.mean((y - y_pred) * X.flatten())
    db = -2 * np.mean(y - y_pred)

    w -= lr * dw
    b -= lr * db

    print(f"Epoch {epoch+1}: Loss = {loss:.2f}")

plt.plot(range(1, epochs + 1), losses)
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training Loss Curve")
plt.show()

def recommend_songs(genre, top_n=5):
    genre = genre.strip().lower()

    if genre not in genre_map:
        print("\nGenre not found")
        print("Available:", list(genre_map.keys()))
        return

    encoded = genre_map[genre]
    filtered = df[df['Genre'] == genre].copy()

    score = (encoded * w + b)[0]
    filtered['Score'] = score

    recommended = filtered.sort_values(by='Score', ascending=False)

    print("\nTop Song Recommendations\n")
    for _, row in recommended.head(top_n).iterrows():
        print(f"{row['Song']} ({row['PlayCount']})")

print("\nAvailable Genres:", list(genre_map.keys()))

genre_input = input("\nEnter genre: ").strip().lower()

recommend_songs(genre_input)